### ISSUE TITLE
Wizard issue

### ISSUE THREAD

**Issue by thisischrys** [reddit-reaper/repository.redditreaper#1]
I'd like to raise a wizard issue, but issues are turned off there.

I use a linux distribution that ships kodi without the necessary repos to install inputstream adaptive.
I keep getting the message that it fails to install every boot (even though I have it installed)

**Comment by reddit-reaper** [comment]
those addons are straight from kodi's repo but on linux to add those extra repos you have to do it when you install it from git so thats probably why
